config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get  '/dash',    to: 'static_pages#dash'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  
  resources :users do
    member do
      get :following, :followers, :stats
    end
  end
  
  root 'static_pages#home'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def dash
    @microposts = Micropost.all
    @users      = User.all
  end
  
  def about
  end
  
  def contact
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>
<p>
  <!-- WTF it is? -->
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>My_App</h1>
<p>
  This is the contact page of the
  <a href="#">My_App</a>
  application.
</p>

app/views/static_pages/dash.html.erb
<% provide(:title, "Dash") %>

<h1>Realtime Dashboard</h1>
  <!-- Dash of the app -->
  <div class="row center">
    <div class="col-md-4 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">Total Wankytimes:</div>
        <div class="panel-body">
          <span class="count"><%= Micropost.all.count %></span>
        </div>
      </div>
    </div>
    
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">Total Wankyusers:</div>
        <div class="panel-body">
          <span class="count"><%= User.all.count %></span>
        </div>
      </div>
    </div>
    
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">Wanky Map:</div>
        <div class="panel-body">
          <p></p><span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span> Your map's coming soon!</p>
          <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d5363928.549073896!2d19.711913812499983!3d48.97051158461561!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1478955558630" 
                  frameborder="0" class="map" allowfullscreen>
          </iframe>
        </div>
      </div>
    </div> 
    
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">Wanky Graph:</div>
        <div class="panel-body">
          <%= line_chart User.group_by_day(:created_at).count %> 
          <%= line_chart Micropost.group_by_day(:created_at).count %>
        </div>
      </div>
    </div> 
  </div>
  

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if logged_in? %>

  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Wankytimes Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
  
<% else %>

  <div class="center jumbotron">
    <h1>Welcome to the Wanky App</h1>
  
    <h2>Sign up now to get a full and free access to the <a href="/">Wanky App</a>! Already <%= Micropost.all.count %> Wanky times have been posted on the App, add yours!</h2>
  
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h2>WankyApp, What is it?</h2>
        <p class="center">WankyApp is a web application that allows you to register all your wanky moments and keep stats about them!</p>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <h2>WankyApp, How does it work?</h2>
        <p class="center"><%= link_to "Sign up now", signup_path %> to access the WankyApp! Once it's done, post your wanky moments, add a comment to each of them and the place you did it! Follow friends if you want to stay updated of their activity and share your stats with everyone you want, easily, through your stats account!</p>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <h2>WankyApp, How many users are registered?</h2>
        <p class="center">Our policy is to be as transparent as possible. You can have <%= link_to "a view", dash_path %> of the number of registered users as well as the total of wanky moments posted on our app.</p>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <h2>WankyApp, Do I keep a total control of the content I post?</h2>
        <p class="center">Of course! You keep a total control of what you post and you can delete the content at every moment. You also can delete your own account but we really hope it will never happen ;)</p>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <h2>Convinced?</h2>
        <p class="center"><%= link_to "Ready to sign up!", signup_path, class: "btn btn-lg btn-primary" %></p>
      </div>
    </div>
  </div>

<% end %>